name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        java: [
          21,
        ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
      - name: mc-publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        if: github.ref == 'refs/heads/release'
        with:
          loaders:
            fabric
            quilt

          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(dev|sources|javadocs).jar

          version-type: release
          changelog-file: CHANGELOG.md

          modrinth-id: 1TowMm2v
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          github-token: ${{ secrets.GIT_TOKEN }}

#          curseforge-id: 123456
#          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"